spring:
  profiles:
    active: default
  application:
    name: backend
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/secondhandplatform
      username: root
      password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8080